### DISCUSSION TITLE
Tensorflow in build

### DISCUSSION THREAD

**Discussion by gnodar01** [CellProfiler/CellProfiler#4721] [Ideas]
From Slack:

@bethac07 :

> The 9000'th person asking when Cellpose is going to be directly available in CellProfiler made me think - Cellpose has a `gpu=False` flag, right? If we never tried to access the GPU, could we put RunCellpose in the main program and then make the plugin RunCellposeWithGPU? That would work, right?

> Ah! There is a [tensorflow-cpu](https://pypi.org/project/tensorflow-cpu/)

@gnodar01 :

> I can't think of any reason it wouldn't work. One caveat is even for cpu only, it's helpful to compile tensorflow for your cpu in particular. Some cpus have special instructions that others don't (eg Advanced Vector Extensions, and other [cpu extensions](https://github.com/tensorflow/tensorflow/issues/7778)), and compiling tensorflow rather than using the pre-built will take advantage of that. The prebuilt will work, it will just be the slowest variant of tensorflow you can get.

> It's also a pretty beefy library, so we'd need to be willing to bump up the size of CellProfiler > 1GB, if I recall the uncompressed size of TF correctly.

@bethac07 :

> That's a totally reasonable limitation/caveat. My guess is though that a slower Cellpose but NOT needing to install Python would be better for, like, 80+% of our users. Devil will be in the details, I'm sure, but glad it's not me being entirely off in the deep end

> And anyone who WANTS to compile their own could do so with the plugin if running from source

@DavidStirling :

> We've actually done this already (for both CellPose and StarDist) on [Glencoe's CellProfiler fork](https://github.com/glencoesoftware/cellprofiler/tree/compat-4-2-ai), with said limitations in mind. A key issue is that it dramatically increases the binary size because torch and tensorflow are huge libraries.

> Loading the plugins also triggers import of these libraries, which slows the startup time noticeably. Our solution there was to modify the plugins to only import cellpose/stardist when the module actually runs.

> One more thing to consider- CellPose and StarDist rely on downloading models from the internet. It may be best to cache those models in the installer so that people don't complain about said model not working when internet goes down/it gets moved in the future. That's easy to do for CellPose, but more tricky for StarDist.

@bethac07 :

> Thanks for the insight! As always, super helpful and useful :slightly_smiling_face:

**Comment by gnodar01** [comment]
For the mac build, we can get some (limited) gpu action through metal: https://developer.apple.com/metal/tensorflow-plugin/.

`conda install -c apple tensorflow-deps` for apple silicon (m1/m2) just ensures you have this `meta.yml` from the [apple channel](https://anaconda.org/apple/tensorflow-deps/files):

```
package:
  name: tensorflow-deps
  version: 2.10.0
build:
  number: '0'
  string: '0'
requirements:
  build: []
  run:
    - grpcio >=1.37.0,<2.0
    - h5py >=3.6.0,<3.7
    - numpy >=1.23.2,<1.23.3
    - protobuf >=3.19.1,<3.20
    - python
about:
  license: Apache2
  license_family: Apache
  summary: Metapackage for installing dependencies of TensorFlow
extra:
  copy_test_source_files: true
  final: true
```
Other than `grpcio`, we already have those dependencies with a normal CP install, so we can skip that step and have the same installation for amd and intel macs.

We'd add these steps for mac builds of CP:

```
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
```

[tensorflow-macos](https://pypi.org/project/tensorflow-macos/) is base TensorFlow, and [tensorflow-metal](https://pypi.org/project/tensorflow-metal/) gets us access to the GPU via [Metal](https://en.wikipedia.org/wiki/Metal_(API)) using TensorFlow's [pluggable device interface](https://blog.tensorflow.org/2021/06/pluggabledevice-device-plugins-for-TensorFlow.html).

Nice part is that Metal is on every Mac, although the underlying GPU resources it utilizes obviously vary.
