### ISSUE TITLE
MeasureColocalization module taking signifcantly longer time to run

### ISSUE THREAD

**Issue by jenna-tomkinson** [CellProfiler/CellProfiler#4768]
**Describe the bug**
I am noticing that the MeasureColocalization module in my pipelines has significantly increased (by about 720%) in run time both `CPU_time` and `wall_time`, compared to just a month ago.

For example, I am currently running a Cell Painting analysis pipeline that has 4 channels, and the MeasureColocalization module (all default parameters) is taking over 2 minutes to run each image (see below):

![image](https://user-images.githubusercontent.com/107513215/231863978-d7550621-8ac1-4559-80eb-fa6e468b8e6d.png)

When I ran this same pipeline on a different dataset with 5 channels (more than the one I am currently running) back on March 1st, it was taking only 20 seconds per images to run (see below):

![image](https://user-images.githubusercontent.com/107513215/231864287-0edefdcd-070c-465c-a822-29bcbd541cbe.png)

I am unsure how this change could occur other than the many different package changes that CellProfiler uses. 

**To Reproduce**
Unfortunately, I am not sure how to best reproduce this other than to give you the different conda environments:

The one I am currently using:
```yml
name: nf1_cellpainting_data

channels:
- conda-forge

dependencies:
# this is restricted to Python 3.8 at this time due to other conflicts
- conda-forge::python=3.8
- conda-forge::ipykernel
- conda-forge::nbconvert=6.4.4
- conda-forge::pip
- conda-forge::numpy
- conda-forge::matplotlib
- conda-forge::pandas
# this package must be hardcoded to work with Mac 
- conda-forge::mysqlclient=1.4.6
- conda-forge::openjdk
# must specifiy scikit-image to avoid error in MeasureGranularity
- conda-forge::scikit-image=0.19.3
- conda-forge::scikit-learn
- conda-forge::mahotas
- conda-forge::gtk2
- conda-forge::typing-extensions
# these are strict because that is how it is on the CellProfiler wiki (Jinja updated for nbconvert)
- conda-forge::Jinja2=3.0.3
- conda-forge::inflect=5.3.0
- conda-forge::wxpython=4.1.0
- conda-forge::sentry-sdk=0.18.0
- pip:
    - cellprofiler==4.2.4
```

The one that was being used a month ago where the CPU and wall times were faster (plus installation of Cellpose and PyTorch):
```yml
name: cp4

channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- pip
- numpy
- matplotlib
- pandas
- mysqlclient
- openjdk
- scikit-learn
- mahotas
- gtk2
- Jinja2=3.0.1
- inflect=5.3.0
- wxpython=4.1.0
- mysqlclient=1.4.4
- sentry-sdk=0.18.0
- ipykernel=6.15.2
- pip:
    - cellprofiler==4.2.4
```

**Expected behavior**
I would expect that with a standard Cell Painting dataset that the MeasureColocalization module will run very slowly when running CellProfiler v4.2.4 installed from pip.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura with M2 chip and on Pop_OS! 22.04LTS
 - CellProfiler Version 4.2.4
 - Installed from source
 - Installed from pypi

**Additional context**
I am just hoping for some advice on what could be causing this significant slow down because this is causing pipelines that should run for 10 hours to run for more than 2 days. No matter what environment I use with CellProfiler, when I install it today with pypi, all of them have the same exact problem with time for MeasureColocalization.

**Comment by callum-jpg** [comment]
This is an intriguing problem but I'm not actually sure of the answer, so I thought I'd write my guess down. What did intrigue me about your conda env is what package manager you are using for different packages. Eg. cellprofiler is installed with pip and some of its dependencies are installed with conda. Did you ever try only installing cellprofiler and its dependencies (though hopefully it installs all of its own dependencies) using pip?

One difference I've just learned between installing packages between pip and conda is that in pip, the maintainers decide how their package is compiled ([example here](https://stackoverflow.com/questions/53197337/running-quicker-for-numpy-and-pandas-installed-via-conda-than-via-pip)). For conda-forge installs, the packages maintainers can be different from the original package authors, so they may decide to use a different compilation configuration.

In your most recent build, you are specifically requesting numpy from conda-forge, but in the older one there is no such request, so (I think) numpy will be downloaded from the default conda channel. So, maybe the default channel numpy is quicker than the conda-forge one for whatever reason (eg compilation configuration changes). Of course, I've used numpy as an example here but it could be some of the other dependencies that MeasureColocalization uses which is causing the slow down.

So I'd recommend installing the requirements from the default channel as before, rather than conda-forge. I'd also be interested to see how installing the dependencies with pip, rather than conda, would perform (though hopefully these dependencies would install themselves with pip install cellprofiler).

**Comment by jenna-tomkinson** [comment]
I just attempted to install CellProfiler with pip without specifically adding the dependencies so that they are installed from pypi and I am still running into the same exact problem where it will take about 140 seconds with the dataset I am using to run the MeasureColocalization module. Here is what the environment looks like:

```yml
name: nf1_test_env

channels:
- conda-forge
- defaults

dependencies:
# this is restricted to Python 3.8 at this time due to other conflicts
- python=3.8
- ipykernel
- nbconvert=6.4.4
- openjdk
- scikit-image=0.19.3
- pip
- pip:
    - cellprofiler==4.2.4
```

I believe this is what you described @callum-jpg, but please let me know if you meant something else.

I will mention that the cp4 environment that comes from the CellProfiler wiki I have modified to include using the cellpose plugin, but it doesn't explain such a dramatic difference when I tested with the same exact dataset just with this test environment.

When I ran this small dataset in March, the compute time was:
```
Mon Mar  6 11:56:13 2023: Image # 1, module MeasureColocalization # 8: CPU_time = 69.42 secs, Wall_time = 5.08 secs
```
But when I ran it again today in the environment above, again, same dataset, this was the compute time:
```
Thu Apr 13 15:46:22 2023: Image # 1, module MeasureColocalization # 8: CPU_time = 251.51 secs, Wall_time = 45.63 secs
```

It is surprising to me how slow it would be with just 3 channels and approximately 15 cells image set.
