### ISSUE TITLE
CellProfiler 4.2.6 can not be installed in conda environment with Python 3.9

### ISSUE THREAD

**Issue by jenna-tomkinson** [CellProfiler/CellProfiler#4906]
CellProfiler 4.2.6 can not be installed in conda environment with Python 3.9
---

**Describe the bug**

@d33bs and I are attempting to install CellProfiler v4.2.6 with Python 3.9 instead of 3.8, and I am running into a `centrosome` error, specifically with numpy. 

```bash
Building wheels for collected packages: centrosome
  Building wheel for centrosome (pyproject.toml): started
  Building wheel for centrosome (pyproject.toml): finished with status 'error'
Failed to build centrosome

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × Building wheel for centrosome (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/outline.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/watershed.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/mode.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/filter.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/zernike.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/bg_compensate.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/index.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/rankorder.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/__init__.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/threshold.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/neighmovetrack.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/propagate.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/radial_power_spectrum.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/cpmorphology.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/kirsch.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/lapjv.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/haralick.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/smooth.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/fastemd.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/otsu.py -> build/lib.linux-x86_64-cpython-39/centrosome
      copying centrosome/princomp.py -> build/lib.linux-x86_64-cpython-39/centrosome
      running build_ext
      building 'centrosome._propagate' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/centrosome
      gcc -pthread -B /home/jenna/mambaforge/envs/cellprofiler_test/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/jenna/mambaforge/envs/cellprofiler_test/include -fPIC -O2 -isystem /home/jenna/mambaforge/envs/cellprofiler_test/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-k77e5tt6/normal/lib/python3.9/site-packages/numpy/core/include -Icentrosome/include -I/home/jenna/mambaforge/envs/cellprofiler_test/include/python3.9 -c centrosome/_propagate.c -o build/temp.linux-x86_64-cpython-39/centrosome/_propagate.o
      centrosome/_propagate.c:1241:10: fatal error: numpy/arrayobject.h: No such file or directory
       1241 | #include "numpy/arrayobject.h"
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for centrosome
ERROR: Could not build wheels for centrosome, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed
```

The environment file we used is as follows:

```yaml
name: cellprofiler_test

channels:
- conda-forge

dependencies:
- conda-forge::python=3.9
- conda-forge::ipykernel
- conda-forge::jupyterlab
- conda-forge::nbconvert=6.4.4
- conda-forge::pip
- conda-forge::numpy=1.25.1
- conda-forge::pyyaml
- conda-forge::matplotlib
- conda-forge::seaborn
- conda-forge::pandas
- conda-forge::mysqlclient
- conda-forge::openjdk
# must specifiy scikit-image to avoid errors in MeasureGranularity
- conda-forge::scikit-image=0.19.3
- conda-forge::scikit-learn
- conda-forge::mahotas
- conda-forge::gtk2
- conda-forge::typing-extensions
# these are strict because that is how it is on the CellProfiler wiki (Jinja updated for nbconvert)
- conda-forge::Jinja2=3.0.3
- conda-forge::inflect=5.3.0
- conda-forge::wxpython=4.2.0
- conda-forge::sentry-sdk=0.18.0
- pip:
    # Install CellProfiler (do not install higher due to possible differences in output)
    - cellprofiler==4.2.6
    - CytoTable
    - pycytominer
```

**To Reproduce**
1. Run the above yml file with mamba or conda to install environment 
2. Expected error printed above with centrosome

**Expected behavior**

The expected behavior is to install CellProfiler using Python 3.9 as 3.8 will reach the end of life in October of this year.

**Desktop (please complete the following information):**
 - OS: Linux PopOS!
 - CellProfiler Version 4.2.6
 - Installed from source
 - Installed from PyPi
