### ISSUE TITLE
Issues in installing python distribution of Cellprofiler==4.2.4 

### ISSUE THREAD

**Issue by arka2696** [CellProfiler/CellProfiler#4942]
Dear Community,

I am encountering difficulties while attempting to install the Python distribution of CellProfiler version 4.2.4. Although I am aware that the latest version available is 4.2.7, I need to install version 4.2.4 to follow the PyCytominer and Profiling tutorial from this repository [https://github.com/WayScience/nf1_schwann_cell_painting_data](url)

I am currently trying to perform this installation on a python 3.8 environment in Ubuntu server 24.04 LTS.

The tutorial’s accompanying .yml file emphasizes the importance of using specific versions of Python and CellProfiler to prevent potential errors. The contents of the .yml file are as follows:

```yaml
name: nf1_cellpainting_data

channels:
- conda-forge

dependencies:
# this is restricted to Python 3.8 at this time due to other conflicts
- conda-forge::python=3.8
- conda-forge::ipykernel
- conda-forge::jupyterlab
- conda-forge::nbconvert=6.4.4
- conda-forge::pip
- conda-forge::numpy
- conda-forge::pyyaml
- conda-forge::matplotlib
- conda-forge::seaborn
- conda-forge::pandas
# this package must be hardcoded to work with Mac 
- conda-forge::mysqlclient=1.4.6
- conda-forge::openjdk
# must specifiy scikit-image to avoid error in MeasureGranularity
- conda-forge::scikit-image=0.19.3
- conda-forge::scikit-learn
- conda-forge::mahotas
- conda-forge::gtk2
- conda-forge::typing-extensions
# these are strict because that is how it is on the CellProfiler wiki (Jinja updated for nbconvert)
- conda-forge::Jinja2=3.0.3
- conda-forge::inflect=5.3.0
- conda-forge::wxpython=4.2.0
- conda-forge::sentry-sdk=0.18.0
- pip:
    # Install CellProfiler (do not install higher due to possible differences in output)
    - cellprofiler==4.2.4
    - CytoTable
    - pycytominer 
```

**This is the error which I am getting when I am trying to install cellprofiler 4.2.4 via the pip command:**

```bash
 (nf1_cellpainting_data) ubuntu@ip-172-31-71-98:~$ pip install cellprofiler==4.2.4
Collecting cellprofiler==4.2.4
  Using cached CellProfiler-4.2.4-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: boto3>=1.12.28 in ./miniconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages (from cellprofiler==4.2.4) (1.35.20)
Collecting cellprofiler-core==4.2.4 (from cellprofiler==4.2.4)
  Using cached cellprofiler_core-4.2.4-py3-none-any.whl.metadata (1.3 kB)
Collecting centrosome==1.2.1 (from cellprofiler==4.2.4)
  Using cached centrosome-1.2.1.tar.gz (619 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      <string>:35: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************
      
      !!
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_convex_hull.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_cpmorphology2.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_fastemd.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_filter.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_lapjv.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: centrosome/_lapjv.pyx:281:12: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      warning: centrosome/_lapjv.pyx:281:18: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
      /tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-8e165s2m/centrosome_f41ce9b0fd4c46a68eb2b3d19810c129/centrosome/_propagate.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
            heap.ptrs[child][k] = new_elem[k]
        heap.items += 1
      
        # restore heap invariant, all parents <= children
        while child>0:
            parent = (child + 1) / 2 - 1 # __parent(i)
                                     ^
      ------------------------------------------------------------
      
      centrosome/heap.pxd:148:31: Cannot assign type 'double' to 'unsigned int'
      Compiling centrosome/_propagate.pyx because it changed.
      Compiling centrosome/_cpmorphology2.pyx because it changed.
      Compiling centrosome/_filter.pyx because it changed.
      Compiling centrosome/_fastemd.pyx because it changed.
      Compiling centrosome/_lapjv.pyx because it changed.
      Compiling centrosome/_convex_hull.pyx because it changed.
      [1/6] Cythonizing centrosome/_convex_hull.pyx
      [2/6] Cythonizing centrosome/_cpmorphology2.pyx
      [3/6] Cythonizing centrosome/_fastemd.pyx
      [4/6] Cythonizing centrosome/_filter.pyx
      [5/6] Cythonizing centrosome/_lapjv.pyx
      [6/6] Cythonizing centrosome/_propagate.pyx
      Traceback (most recent call last):
        File "/home/ubuntu/miniconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubuntu/miniconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/miniconda3/envs/nf1_cellpainting_data/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-84v9t3bj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-84v9t3bj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-84v9t3bj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 89, in <module>
        File "/tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-84v9t3bj/normal/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: centrosome/_propagate.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 
```

I would appreciate any guidance or suggestions to help resolve this issue

Thank you in advance for your support.

Best regards,
Arka
